repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.7
    hooks:
      - id: ruff
        args: [--fix]
        exclude: ^examples/
      - id: ruff-format
        exclude: ^examples/
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.13.0
    hooks:
      - id: mypy
        exclude: ^examples/
        additional_dependencies:
          - pyarrow>=14.0.0
          - pyiceberg>=0.6.0
