repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-ast
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-toml

  - repo: https://github.com/asottile/add-trailing-comma
    rev: v3.1.0
    hooks:
      - id: add-trailing-comma

  - repo: https://github.com/crate-ci/typos
    rev: v1.40.0
    hooks:
      - id: typos

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.9
    hooks:
      - id: ruff
        args: [--fix, "--config=pyproject.toml"]
        exclude: ^examples/
      - id: ruff-format
        args: ["--config=pyproject.toml"]
        exclude: ^examples/

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.13.0
    hooks:
      - id: mypy
        exclude: ^examples/
        additional_dependencies:
          - pyarrow>=18.0.0
          - pyiceberg>=0.7.1

  - repo: local
    hooks:
      - id: black
        name: Format with Black (disabled)
        entry: "true"
        language: system
        pass_filenames: false
        stages: [manual]
        types: [python]
        files: ^(src/iceberg_loader|tests)/
